### ISSUE TITLE
Not polling for new emails after upgrading from v0.16.2 to v0.16.3

### ISSUE THREAD

**Issue by Zaedus** [LeanderBB/you-have-mail#47] opened 2024-08-20 18:17 UTC
When updating to the new version I might get one notification *if* I open the app, but no more after that without manually polling. In the app, it will sometimes have been a whole day since it last polled. Looking at the diff between these versions, a lot of code that handles this has changed. I've opted to downgrade to v0.16.2 since I need to know when I get an email.

Edit: I am running GrapheneOS on a Pixel 7a

**Comment by LeanderBB** [comment] 2024-08-21 05:16
Hey, thanks for the report. For me this has been working pretty consistently so far on a Pixel 6 with Graphene OS. I have my poll interval set to 15 min.

What I have noticed is that if I don't touch the phone for a long period of time the phone will enter a [doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby) and work scheduled with `WorkManager` will be delayed by the OS. 

@Zaedus Are you sure you don't mean between v0.15 and v0.16.x? Not a lot has changed between 0.16.2 and 0.16.3. In fact if you run 0.16.2 you are more likely to miss the notifications all together.


Could you folks share your logs and your poll intervals?

**Comment by LeanderBB** [comment] 2024-08-21 15:27
@julianfairfax could you try running with a poll interval >= 15 min to see if the experience improves? 

There are 2 types of workers currently in use. For anything < 15 min I need to use a different type of worker. If the experience improves, there may be an issue with the shorter poll intervals.

**Comment by something15525** [comment] 2024-08-22 01:53
I've been having this issue as well in a Pixel 7 Pro running GrapheneOS, with a polling interval of 5 min. Lemme try 15 min and see if that makes things more reliable.

**Comment by LeanderBB** [comment] 2024-08-22 06:04
I have installed the app on a Pixel 3a at 5 min. Will see how it fares during the day against my main phone at 15min.

**Comment by LeanderBB** [comment] 2024-08-22 14:58
Confirmed the issue. I recommend everyone stay on the >= 15 min intervals until the fix is out.

**Comment by LeanderBB** [comment] 2024-08-22 18:20
This should be addressed in [v0.16.4](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.16.4). Let me know if it fixes the issue.

However, do keep in mind that if the phone enter doze mode the poll work will be delayed by the OS to preserve battery life regardless of poll interval.

**Comment by something15525** [comment] 2024-08-26 17:57
Can confirm a 15 min interval fixed if for me. @LeanderBB thanks for the quick fix!

**Comment by Zaedus** [comment] 2024-09-05 23:05
Latest version fixed the bug for me!

**Comment by LeanderBB** [comment] 2024-09-06 14:23
Perfect. Thanks for the feedback :).

**Closed by LeanderBB** 2024-09-06 14:23 UTC
Labels: bug

**Comment by something15525** [comment] 2024-09-06 14:48
Works for me as well, thanks for the fix!
