### ISSUE TITLE
No notifications on email replies

### ISSUE THREAD

**Issue by ramonls8** [LeanderBB/you-have-mail#38] opened 2024-01-17 11:08 UTC
Notifications when a new email arrives work correctly, however no notification appears when someone sends a reply email to an email you have previously sent them.

**Comment by LeanderBB** [comment] 2024-01-18 08:05
Hey, thanks for the report. Confirmed the issue. Will investigate.

**Comment by LeanderBB** [comment] 2024-01-19 17:09
@ramonls8 I just tried to reproduced the issue so I can look at why it's broken, but so far I am unable to reproduce this. 

I've tried with 2 separate accounts and they all report the email.

Is it possible that you mark incoming email as read with some automated rule?

**Comment by ramonls8** [comment] 2024-01-19 18:02
I reinstalled the app and now I am receiving all notifications. I don't know why it didn't work before. Sorry for the trouble.

**Comment by LeanderBB** [comment] 2024-01-19 18:08
It's possible the background service may have been terminated. 

I'll close this ticket for now. Feel free to re-open if it happens again.

**Closed by LeanderBB** 2024-01-19 18:08 UTC
Labels: can't reproduce
